import {
  Zap,
  Gauge,
  Triangle,
  Scale,
  Database,
  GitBranch,
  Mail,
  TrafficCone,
  Target,
  Shield,
  Blocks,
  HardDrive,
  Link,
  TrendingUp,
  Building2,
  ClipboardList,
  Compass,
  Calculator,
  Lightbulb,
  BookOpen,
  LayoutGrid,
  FileText,
  Star,
  Rocket,
  CheckCircle,
  Circle,
  XCircle,
  Search,
  Menu,
  PenLine,
  ChevronDown,
  Info,
} from 'lucide-react';

const icons = {
  zap: Zap,
  gauge: Gauge,
  triangle: Triangle,
  scale: Scale,
  database: Database,
  'git-branch': GitBranch,
  mail: Mail,
  'traffic-cone': TrafficCone,
  target: Target,
  shield: Shield,
  blocks: Blocks,
  'hard-drive': HardDrive,
  link: Link,
  'trending-up': TrendingUp,
  building: Building2,
  'clipboard-list': ClipboardList,
  compass: Compass,
  calculator: Calculator,
  lightbulb: Lightbulb,
  'book-open': BookOpen,
  'layout-grid': LayoutGrid,
  'file-text': FileText,
  star: Star,
  rocket: Rocket,
  'check-circle': CheckCircle,
  circle: Circle,
  'x-circle': XCircle,
  search: Search,
  menu: Menu,
  'pen-line': PenLine,
  'chevron-down': ChevronDown,
  info: Info,
};

export default function Icon({ name, size = 20, className = '', strokeWidth = 2 }) {
  const Component = icons[name];
  if (!Component) return null;
  return <Component size={size} className={className} strokeWidth={strokeWidth} />;
}
